# Site settings
title: Matt Baker
description: GIS Solutions Architect
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Matt Baker
user_description: I am a Minnesota based GIS Solutions Architect with ten years of experience developing and maintaining spatial applications for local, state, and national government agencies. Although I still open an IDE or desktop GIS software on occasion, I now spend most of my time defining, coordinating, and implementing governance and technology within an enterprise GIS environment. I also <i>very</i> occasionally <a href="https://medium.com/@mbaker">blog</a> about GIS. To contact me, please use <a href="https://www.linkedin.com/in/mattjbaker">LinkedIn</a>.

user_title: GIS Solutions Architect
email: contact@8ofr.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
